version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: backend-app
    ports:
      - "3001:3001"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
